<?php

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;
// echo INSTALL_PATH.'/assets/fellow/phpmailer/Exception.php';
require(INSTALL_PATH.'/assets/fellow/phpmailer/Exception.php');
require(INSTALL_PATH.'/assets/fellow/phpmailer/PHPMailer.php');
require(INSTALL_PATH.'/assets/fellow/phpmailer/SMTP.php');

function delivermail($ntcode, $toid, $cntaddarr = '') {
    global $db, $cfgrow, $bpprow;

    if (!defined('ISDEMOMODE')) {
        // load message
        $msgRow = array();
        $row = $db->getAllRecords(DB_TBLPREFIX . '_notifytpl', '*', ' AND ntcode = "' . $ntcode . '"');
        foreach ($row as $value) {
            $msgRow = array_merge($msgRow, $value);
        }

        // populate array
        $cntarr = array();
        $cntarr = array_merge($bpprow, $cntarr);
        $cntarr = array_merge($cfgrow, $cntarr);
        if ($toid > 0) {
            // Get member details
            $mbrdata = getmbrinfo($toid);
            $cntarr = array_merge($mbrdata, $cntarr);
            $emailtoname = $mbrdata['firstname'] . ' ' . $mbrdata['lastname'];
            $emailtoaddr = $mbrdata['email'];
        } else {
            $emailtoname = $cfgrow['site_emailname'];
            $emailtoaddr = $cfgrow['site_emailaddr'];
        }
        $cntarr = array_merge((array) $cntaddarr, $cntarr);

        if ($toid < 1 || $mbrdata['optinme'] == 1) {

            // parse content
            $msgsubject = parsenotify($cntarr, $msgRow['ntsubject']);
            $msgtext = parsenotify($cntarr, $msgRow['nttext']);
            // $msghtml = parsenotify($cntarr, $msgRow['nthtml']);
            $http= EMAIL;
            $msghtml= <<<INI_HTML
                <p>Hello {$mbrdata['firstname']},</p>
                <p><b>Welcome and thank you for registering!</b></p><br>
                        <p>Your Account Details:<br>
                        Name: {$emailtoname}<br>
                        Email: {$emailtoaddr}<br>
                        <p>Please click on the link to verfiy your email address 
                <a href="http://{$http}member/verify_email.php?user_id={$toid}
                &token={md5($emailtoname)}">Click Here </></p>
                        <p><br>
                        Best Regards,<br>
                        Immortal Success<br>
                        &nbsp;</p>
INI_HTML;
            // Instantiation and passing `true` enables exceptions
            // $mail = new PHPMailer();
            $mail = new PHPMailer\PHPMailer\PHPMailer(true);

            try {
                // $mail->isSMTP();
                // $mail->Host = 'mail.doliyastore.com';
                // $mail->SMTPAuth = true;
                // $mail->Username = 'info@doliyastore.com'; //paste one generated by Mailtrap
                // $mail->Password  = '0ALF-8$EY.gv'; //paste one generated by Mailtrap
                // $mail->SMTPSecure = 'tls';
                // $mail->Port = 587;

                $mail->isSMTP();
                $mail->Host = 'smtp.hostinger.in';
                $mail->SMTPAuth = true;
                $mail->Username = 'no-reply@immortalsuccess.com'; //paste one generated by Mailtrap
                $mail->Password  = 'Admin@1122!'; //paste one generated by Mailtrap
                $mail->SMTPSecure = 'tls';
                $mail->Port = 587;

                //Set who the message is to be sent from
                $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                // $mail->addReplyTo('no-reply@immortalsuccess.com', 'Immortalsuccess');

                //Set who the message is to be sent from
                // $mail->setFrom($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                //Set an alternative reply-to address
                //$mail->addReplyTo($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                //Set who the message is to be sent to
                $mail->addAddress($emailtoaddr, $emailtoname);
                //Set the subject line
                $mail->Subject = $msgsubject;
                //Read an HTML message body from an external file, convert referenced images to embedded,
                //convert HTML into a basic plain-text alternative body
                $mail->msgHTML($msghtml, __DIR__);
                $mail->IsHTML(true); 
                $mail->CharSet="utf-8";
                //Replace the plain text body with one created manually
                // $mail->AltBody = $msgtext;
                //Attach an image file
                //$mail->addAttachment('images/phpmailer_mini.png');
                //send the message, check for errors
                if (!$mail->send()) {
                    // echo 'mailer.do', "Mailer Error ({$msgsubject}): {$mail->ErrorInfo}";
                    printlog('mailer.do', "Mailer Error ({$msgsubject}): {$mail->ErrorInfo}");
                } else {
                    // echo 'mailer.do', "Message sent ({$msgsubject})!";
                    printlog('mailer.do', "Message sent ({$msgsubject})!");
                }
            } catch (Exception $e) {
                printlog('mailer.do', "Message ({$msgsubject}) could not be sent. Mailer Error: {$mail->ErrorInfo}");
            }
        }
    }
}


function resetPasswordmail($ntcode, $toid, $cntaddarr = '') {
    global $db, $cfgrow, $bpprow;

    if (!defined('ISDEMOMODE')) {

        // load message
        $msgRow = array();
        $row = $db->getAllRecords(DB_TBLPREFIX . '_notifytpl', '*', ' AND ntcode = "' . $ntcode . '"');
        foreach ($row as $value) {
            $msgRow = array_merge($msgRow, $value);
        }

        // populate array
        $cntarr = array();
        $cntarr = array_merge($bpprow, $cntarr);
        $cntarr = array_merge($cfgrow, $cntarr);
        if ($toid > 0) {
            // Get member details
            $mbrdata = getmbrinfo($toid);
            $cntarr = array_merge($mbrdata, $cntarr);
            $emailtoname = $mbrdata['firstname'] . ' ' . $mbrdata['lastname'];
            $emailtoaddr = $mbrdata['email'];
        } else {
            $emailtoname = $cfgrow['site_emailname'];
            $emailtoaddr = $cfgrow['site_emailaddr'];
        }
        $cntarr = array_merge((array) $cntaddarr, $cntarr);

        if ($toid < 1 || $mbrdata['optinme'] == 1) {

            // parse content
            $msgsubject = parsenotify($cntarr, $msgRow['ntsubject']);
            $msgtext = parsenotify($cntarr, $msgRow['nttext']);
            $msghtml = parsenotify($cntarr, $msgRow['nthtml']);

            // Instantiation and passing `true` enables exceptions
            $mail = new PHPMailer\PHPMailer\PHPMailer(true);

            try {
                $mail->isSMTP();
                $mail->Host = 'smtp.hostinger.in';
                $mail->SMTPAuth = true;
                $mail->Username = 'no-reply@immortalsuccess.com'; //paste one generated by Mailtrap
                $mail->Password  = 'Admin@1122!'; //paste one generated by Mailtrap
                $mail->SMTPSecure = 'tls';
                $mail->Port = 587;

                //Set who the message is to be sent from
                $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                // $mail->addReplyTo('no-reply@immortalsuccess.com', 'Immortalsuccess');

                //Set who the message is to be sent from
                // $mail->setFrom($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                // $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                //Set an alternative reply-to address
                //$mail->addReplyTo($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                //Set who the message is to be sent to
                $mail->addAddress($emailtoaddr, $emailtoname);
                //Set the subject line
                $mail->Subject = $msgsubject;
                //Read an HTML message body from an external file, convert referenced images to embedded,
                //convert HTML into a basic plain-text alternative body
                $mail->msgHTML($msghtml, __DIR__);
                $mail->IsHTML(true); 
                $mail->CharSet="utf-8";
                //$mail->addAttachment('images/phpmailer_mini.png');
                //send the message, check for errors
                if (!$mail->send()) {
                    printlog('mailer.do', "Mailer Error ({$msgsubject}): {$mail->ErrorInfo}");
                } else {
                    printlog('mailer.do', "Message sent ({$msgsubject})!");
                }
            } catch (Exception $e) {
                printlog('mailer.do', "Message ({$msgsubject}) could not be sent. Mailer Error: {$mail->ErrorInfo}");
            }
        }
    }
}
function validatemail($toemail,$recivername,$user_id='') {
    global $db, $cfgrow, $bpprow;

    if (!defined('ISDEMOMODE')) {
        // load message
        $msgRow = array('nthtml'=>'<p>Welcome</p>');

        $status='';
        // populate array
        $cntarr = array();
        $cntarr = array_merge($bpprow, $cntarr);
        $cntarr = array_merge($cfgrow, $cntarr);

        $cntarr = array_merge((array) $cntaddarr, $cntarr);

            // parse content
            $msgsubject = parsenotify($cntarr, $msgRow['ntsubject']);
            $msgtext = parsenotify($cntarr, $msgRow['nttext']);
            // $msghtml = parsenotify($cntarr, $msgRow['nthtml']);
                        $http= EMAIL;
            $msghtml= <<<INI_HTML
                <p>Hello {$recivername},</p>
                <p><b>Welcome and thank you for updating with Immortal Success!</b></p><br>
                        <p>Please click on the link to verfiy your email address 
                <a href="http://{$http}member/verify_email.php?user_id={$user_id}
                &token={md5($recivername)}">Click Here </></p>
                        <p><br>
                        Best Regards,<br>
                        Immortal Success<br>
                        &nbsp;</p>
INI_HTML;

            // Instantiation and passing `true` enables exceptions
            // $mail = new PHPMailer();
            $mail = new PHPMailer\PHPMailer\PHPMailer(true);

            try {
                // $mail->isSMTP();
                // $mail->Host = 'mail.doliyastore.com';
                // $mail->SMTPAuth = true;
                // $mail->Username = 'info@doliyastore.com'; //paste one generated by Mailtrap
                // $mail->Password  = '0ALF-8$EY.gv'; //paste one generated by Mailtrap
                // $mail->SMTPSecure = 'tls';
                // $mail->Port = 587;

                $mail->isSMTP();
                $mail->Host = 'smtp.hostinger.in';
                $mail->SMTPAuth = true;
                $mail->Username = 'no-reply@immortalsuccess.com'; //paste one generated by Mailtrap
                $mail->Password  = 'Admin@1122!'; //paste one generated by Mailtrap
                $mail->SMTPSecure = 'tls';
                $mail->Port = 587;

                //Set who the message is to be sent from
                    //Set who the message is to be sent from
                $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                // $mail->addReplyTo('no-reply@immortalsuccess.com', 'Immortalsuccess');
                // $mail->setFrom('info@doliyastore.com', 'Immortal Success');
                //Set an alternative reply-to address
                // $mail->addReplyTo($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                //Set who the message is to be sent to
                $mail->addAddress($toemail, $recivername);
                //Set the subject line
                $mail->Subject = 'Welcome';
                //Read an HTML message body from an external file, convert referenced images to embedded,
                //convert HTML into a basic plain-text alternative body
                $mail->msgHTML($msghtml, __DIR__);
                //Replace the plain text body with one created manually
                $mail->AltBody = 'Welcome to Immortal Success';
                //Attach an image file
                //$mail->addAttachment('images/phpmailer_mini.png');
                //send the message, check for errors
                if (!$mail->send()) {
                    // var_dump($mail->ErrorInfo);exit();
                    $status = false;
                    // printlog('mailer.do', "Mailer Error ({$msgsubject}): {$mail->ErrorInfo}");
                } else {
                    $status=true;
                    // echo 'mailer.do', "Message sent ({$msgsubject})!";
                    // printlog('mailer.do', "Message sent ({$msgsubject})!");
                }
            } catch (Exception $e) {
                printlog('mailer.do', "Message ({$msgsubject}) could not be sent. Mailer Error: {$mail->ErrorInfo}");
            }
        
    }
    return $status;
}
