<?php
// echo SURL;
// echo INSTALL_PATH.'/assets/fellow/phpmailer/Exception.php';
// require(INSTALL_PATH.'/assets/fellow/phpmailer/Exception.php');
// require(INSTALL_PATH.'/assets/fellow/phpmailer/PHPMailer.php');
// require(INSTALL_PATH.'/assets/fellow/phpmailer/SMTP.php');
require 'PHPMailer/PHPMailerAutoload.php';

if(isset($_POST['submit'])){
	$emailtoname = $_POST['name'];
	$emailtoaddr = $_POST['email'];
	$mobile = $_POST['mobile'];
	$msgsubject = $_POST['query'];
	$content = $_POST['msg'];
	$msghtml='<p>'.$content.'</p><br>'.'<b>Username: </b>'.$emailtoname.'<br><b>Conatact Number:</b> '.$mobile.'<br> <b>Email Address:</b> '.$emailtoaddr.' ';
	// require 'PHPMailer/PHPMailerAutoload.php';
	// $mail = new PHPMailer;
	// $mail->isSMTP();
	// $mail->Host = ''; // Which SMTP server to use.
	// $mail->SMTPAuth = true; // Whether you need to login. This is almost always required.
	// //$mail->SMTPSecure = 'tls'; // Which security method to use. TLS is most secure.
	// $mail->Port = 25; // Which port to use, 587 is the default port for TLS security.
	// $mail->Username = "no-reply@immortalsuccess.com"; // Your mail username.
	// $mail->Password = "Admin@1122!"; // Your mail Password.

	// /*
	//  * Message Configuration
	//  */

	// $mail->setFrom('unschool.in', 'unschool.in'); // Set the sender of the message.
	// $mail->addAddress($email, $name); // Set the recipient of the message.
	// $mail->Subject = 'Successfull';
	// $mail->isHTML(true);
	// $mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
	// 				<p>This is a test email I am sending using SMTP mail server with PHPMailer.</p>";
	// $mail->Body = $mailContent;
	// if ($mail->send()) {
	// 	header("Location: ../../contact/thanks.html");
	// }else {
	// 	echo "<span style='color:tomato'>Mailer Error: " . $mail->ErrorInfo."</span><br />";
	// 	exit();
	// 	header("Location: http://localhost/landing_page/UNSHCOOL/www.unschool.in/contact/index.html");
		
	// }

            // $mail = new PHPMailer\PHPMailer\PHPMailer(true);
	$mail = new PHPMailer;

            try {
                $mail->isSMTP();
                $mail->Host = 'smtp.hostinger.in';
                $mail->SMTPAuth = true;
                $mail->Username = 'no-reply@immortalsuccess.com'; //paste one generated by Mailtrap
                $mail->Password  = 'Admin@1122!'; //paste one generated by Mailtrap
                $mail->SMTPSecure = 'tls';
                $mail->Port = 587;

                //Set who the message is to be sent from
                $mail->setFrom('no-reply@immortalsuccess.com', 'Immortalsuccess');
                $mail->addReplyTo('no-reply@immortalsuccess.com', 'Immortalsuccess');
                //Set an alternative reply-to address
                //$mail->addReplyTo($cfgrow['site_emailaddr'], $cfgrow['site_emailname']);
                //Set who the message is to be sent to
                $mail->addAddress('info@immortalsuccess.com','Immortalsuccess');
                //Set the subject line
                $mail->Subject = $msgsubject;
                //Read an HTML message body from an external file, convert referenced images to embedded,
                //convert HTML into a basic plain-text alternative body
                $mail->msgHTML($msghtml, __DIR__);
                $mail->Body = $msghtml;
                $mail->IsHTML(true); 
                $mail->CharSet="utf-8";
                //Replace the plain text body with one created manually
                // $mail->AltBody = $msgtext;
                //Attach an image file
                //$mail->addAttachment('images/phpmailer_mini.png');
                //send the message, check for errors
                if (!$mail->send()) {
                   	echo "<span style='color:tomato'>Mailer Error: " . $mail->ErrorInfo."</span><br />";
						exit();
                } else {
                    // echo 'mailer.do', "Message sent ({$msgsubject})!";
                  header("Location: ../../contact/thanks.html");
                }
            } catch (Exception $e) {
                printlog('mailer.do', "Message ({$msgsubject}) could not be sent. Mailer Error: {$mail->ErrorInfo}");
            }
   }
exit;
